Main change status
SvenjaKlenke/zoofoo-teamproject pull request #16
Opened 2023-05-25 14:54 UTC by RichardDev101

Simulate days of the week and changes the states of animals.

2023-05-26 09:43 UTC, Kreyno93 commented
please resolve conflicts first 👍🏻

2023-05-30 15:57 UTC, Kreyno93 commented
_"Simulate days of the week and changes the states of animals." kurz auf deutsch
Damit meint ihr dass ihr nur die Wochentage durchgeht und nicht noch die tiere mittels "@put" auf andere Tage setzen könnt oder? denn das verstehe ich unter "changes the states of animals"_

okay nevermind.

Ihr wollt mit dem "seiten wechsel" die tiere die dort aufgelistet sind, ihren jeweiligen Status auf den Tag setzen, auf den man Scrollt?
Meine intuition hat nämlich gerade das Feature so verstanden, dass man durch ne große Liste Animals blättert. und mir die Tiere angezeigt werden die Montags, oder Mittwochs behandelt werden sollen. Stattdessen bestimmt das Blättern bei *allen* Tieren dass der Tag von denen geändert wird?

2023-05-31 10:12 UTC, RichardDev101 commented
Hallo Michael, mit dem Blättern der Wochentagen wollen wir quasi einen Kalender Simulieren. Mit jedem neuen Tage wird der Feed-Status der Tiere geändert die am jeweiligen Tag gefüttert werden müssen. Man blättert also nicht durch alle Tiere.

2023-05-31 12:06 UTC, Kreyno93 commented on backend/src/main/java/de/neuefische/backend/controller/ControllerZooFoo.java
> +    @PutMapping({"animal/{id}"})
no curly brackets required

2023-05-31 12:13 UTC, Kreyno93 requested changes

2023-05-31 12:13 UTC, Kreyno93 commented on backend/src/test/java/de/neuefische/backend/controller/ControllerZooFooTest.java
> +                .isNotBlank();
no need for Object mapper. U just checked the id in the expect part content().json

2023-05-31 12:13 UTC, Kreyno93 commented on backend/src/test/java/de/neuefische/backend/controller/ControllerZooFooTest.java
> +                    .andExpect(jsonPath("$.id").isNotEmpty())
no need to check. u can cleary see that the id is set

2023-05-31 12:13 UTC, Kreyno93 approved these changes

2023-05-31 12:23 UTC, merged