Change status by choosing a keeper
SvenjaKlenke/zoofoo-teamproject pull request #31
Opened 2023-06-05 10:21 UTC by KMarienfeld

2023-06-05 11:22 UTC, Kreyno93 requested changes

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalCard/AnimalCard.tsx
>      animals: Animal
i would raname it to what it represents in the end
your animals is a singular animal...
propably be better to rename it to just 'animal'

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalCard/AnimalCard.tsx
> +    keeper: Keeper[]
the other way around, your singular keeper is an array of keeper
better to rename it to 'keepers' or 'listOfKeepers', 'keepersArray'

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalGallery/FeedingGallery.tsx
> +    useEffect(getAllKeepers, [])
do you need the useEffect? for every single Gallery?
u could outsource it to highest component and give the list of keepers as props down to the others

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalGallery/ToFeedGallery.tsx
> +    useEffect(getAllKeepers, [])
same

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalGallery/FedGallery.tsx
> +    useEffect(getAllKeepers, [])
same

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/AnimalGallery/FeedingGallery.tsx
> +    useEffect(getAllKeepers, [])
u could save a lot of requests outsource the api call

2023-06-05 11:22 UTC, Kreyno93 commented on frontend/src/App.tsx
> +                                <FedGallery animalsFed={feedingDone} getAllAnimals={getAllAnimals}/>
one possible solution for the many useEffects: u could render just one big component which has all these components in it. therefore u can make the calls in upper levels and reach it down to the lower ones, instead of using a useEffect in every single Gallery for the keepers. just like u did with the getAllAnimals

2023-06-05 16:37 UTC, SvenjaKlenke commented on frontend/src/AnimalCard/AnimalCard.tsx
>      animals: Animal
done

2023-06-05 16:37 UTC, SvenjaKlenke commented on frontend/src/AnimalCard/AnimalCard.tsx
> +    keeper: Keeper[]
done

2023-06-05 16:37 UTC, SvenjaKlenke commented on frontend/src/AnimalGallery/FeedingGallery.tsx
> +    useEffect(getAllKeepers, [])
done

2023-06-06 08:25 UTC, Kreyno93 approved these changes

2023-06-06 09:03 UTC, merged

2023-06-06 09:04 UTC, AccessCoder approved these changes